# Generated by Django 3.1.4 on 2021-01-15 02:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('courseName', models.CharField(max_length=200)),
                ('courseCode', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=20)),
                ('gradeNote', models.CharField(max_length=1000)),
                ('credits', models.IntegerField(null=True)),
                ('exam', models.CharField(max_length=1000)),
                ('calculator', models.BooleanField()),
                ('author', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('editionYear', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(blank=True)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), size=7)),
                ('name', models.CharField(max_length=10)),
                ('timestart', models.CharField(blank=True, max_length=30)),
                ('timeend', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(blank=True, choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('lab', 'Lab')], max_length=10)),
                ('studentPerSupervisor', models.CharField(blank=True, max_length=10)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('safetyTaught', models.BooleanField()),
                ('safetyExamined', models.BooleanField()),
                ('outline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('coordinator', 'Coordinator'), ('ta', 'Ta')], max_length=15)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('section', models.CharField(max_length=10)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ap', models.FloatField()),
                ('A', models.FloatField()),
                ('Am', models.FloatField()),
                ('Bp', models.FloatField()),
                ('B', models.FloatField()),
                ('Bm', models.FloatField()),
                ('Cp', models.FloatField()),
                ('C', models.FloatField()),
                ('Cm', models.FloatField()),
                ('Dp', models.FloatField()),
                ('D', models.FloatField()),
                ('outline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseOutcome', models.CharField(max_length=200)),
                ('attribute', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12')], max_length=10)),
                ('level', models.CharField(blank=True, choices=[('I', 'I'), ('D', 'D'), ('A', 'A')], max_length=3)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseOutcomes', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('weight', models.FloatField()),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='AU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.FloatField()),
                ('naturalScience', models.FloatField()),
                ('complementary', models.FloatField()),
                ('engineerScience', models.FloatField()),
                ('engineerDesign', models.FloatField()),
                ('outline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AU', to='api.courseoutline')),
            ],
        ),
    ]
